---  # tasks file for rkhunter

- name: Install rkhunter
  ansible.builtin.package:
    name: rkhunter
    update_cache: true
    state: latest
  tags:
    - install
    - rkhunter
    - rkhunter-install

- name: Create temp directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/rkhunter/tmp
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - install
    - rkhunter
    - rkhunter-install

- name: Configure /etc/rkhunter.conf.local
  ansible.builtin.copy:
    dest: /etc/rkhunter.conf.local
    content: 'ALLOW_SSH_PROT_V1=2'
    mode: '0644'
    owner: root
    group: root
  tags:
    - configuration
    - rkhunter
    - rkhunter-configuration

- name: Configure /etc/rkhunter.conf
  template:
    src: "etc/rkhunter.conf.j2"
    dest: /etc/rkhunter.conf
    owner: root
    group: root
    mode: 0644
  notify: update rkhunter
  tags:
    - configuration
    - rkhunter
    - rkhunter-configuration

- name: Configure /etc/default/rkhunter
  template:
    src: etc/default/rkhunter.j2
    dest: /etc/default/rkhunter
    owner: root
    group: root
    mode: 0644
  notify: update rkhunter
  tags:
    - configuration
    - rkhunter
    - rkhunter-configuration

- name: rkhunter update
  command: rkhunter --update
  register: rkhunter_update
  failed_when: rkhunter_update.rc != 2 and rkhunter_update.rc != 0
  changed_when: false
  tags:
    - update
    - rkhunter
    - rkhunter-update
